### ISSUE TITLE
complex join, parallels, forking 

### ISSUE THREAD

**Issue by thejmazz** [bionode/bionode-waterwheel#16]

**Comment by tiagofilipe12** [comment]
This issue is also addressed in #73 tests and in several test pipelines were added to pipelines in #70 and #72. Pipeline shapes for test pipelines became documented in commit [ba46e67](https://github.com/bionode/bionode-watermill/pull/76/commits/ba46e67bf8e36d98cd8cff810cdf91f1247ba4f8). Shall we close this too, @thejmazz ?

**Comment by thejmazz** [comment]
Yeah lets close, we can make more test issues in the future with more specific goals
